### ISSUE TITLE
CUDA VERSION MISMATCH

### ISSUE THREAD

**Issue by cevatbostancioglu** [lhk/darknet_wrapper#1]
Hello , i have cuda-8.0 so when i run cmake .. command i just saw

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA: Found unsuitable version "8.0", but required is exact
  version "7.5" (found /usr/local/cuda-8.0)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:949 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:48 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:291 (find_host_package)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/cevat/darknet_orj/darknet_wrapper/build/CMakeFiles/CMakeOutput.log".
See also "/home/cevat/darknet_orj/darknet_wrapper/build/CMakeFiles/CMakeError.log".

how i can solve this .

Thank you.

**Comment by lhk** [comment]
That's a strange problem.
I'm using 8.0, too and it compiles fine for me.

And I'm surprised by the CMake error, which complains about an exact requirement. In the CMakeLists.txt, cuda is required, but there is no restriction on the version.
Hard to debug this kind of problem on someone else's PC.

Some things you could try:

Googling your error turns up this stackoverflow question:
https://stackoverflow.com/questions/41198864/error-using-cmake

The solution was a problem with opencv/cuda compatibility.
Did you install opencv with our script ?
That would do a clean installation with the correct source.

Some other things:

1. Are you running this exact CMake, or did you integrate this code into something else.
Because in the CMakeLists.txt from this wrapper, version 8 should be perfectly fine.

2. Maybe you have multiple conflicting versions of cuda.

go to usr/local and take a look at the cuda folders.
There should be a `cuda-8.0` and a symlink `cuda`. The symlink should point to your `cuda-8.0 `folder.
So  `cat /usr/local/cuda/version.txt` should print something with an 8.
Does it do that ?
If the symlink is not there, or if it is broken, point it to cuda-8.0

**Comment by sjdrc** [comment]
It looks like you might have compiled OpenCV with CUDA 7.5, I'd check that out first.

**Comment by lhk** [comment]
Closing this now. If you still have problems, feel free to reopen
